name: Generate trophy card

on:
  schedule:
    - cron: "0 */12 * * *" # Triggers safely twice a day

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Trophies
        uses: ryo-ma/github-profile-trophy@master # Official action package that doesn't crash
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: trophy-output # Automatically builds and pushes directly to your trophy-output branch
