name: GitHub Trophy

on:
  schedule:
    - cron: '0 0 * * *' # Runs automatically every midnight
  workflow_dispatch: # Keeps manual trigger active

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Deploy GitHub Profile Trophy
        uses: ryo-ma/github-profile-trophy@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: trophy-output
